apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-webapp
  template:
    metadata:
      labels:
        app: devops-webapp
    spec:
      containers:
      - name: devops-webapp
        image: goldissalar/devops-webapp:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
  strategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: devops-webapp-service
spec:
  selector:
    app: devops-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

---
#passt anzahl an replicas an basierend auf die cpu
  apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: web-app-hpa
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: devops-webapp
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 30

---
